### ISSUE TITLE
using ember-cli-yadda with ember-cli-blanket 'Error: Could not find module yadda'

### ISSUE THREAD

**Issue by sfbwalder** [curit/ember-cli-yadda#15]
We have installed the latest versions of ember-cli-yadda and ember-cli-blanket, with ember-cli 1.13.8.  When running /tests without blanket coverage the BDD tests run fine.  When running /tests?coverage to enable blanket coverage, the BDD tests fail with:

```
Died on test #1     at Object.TestLoader.moduleLoadFailure (http://localhost:4200/assets/test-support.js:5854:11)
    at Object.TestLoader.require (http://localhost:4200/assets/test-loader.js:31:14)
    at Object.TestLoader.loadModules (http://localhost:4200/assets/test-loader.js:21:18)
    at Function.TestLoader.load (http://localhost:4200/assets/test-loader.js:40:24)
    at http://localhost:4200/assets/test-support.js:5863:16: Could not find module yadda@ 1 ms
Source:     
Error: Could not find module yadda
    at missingModule (http://localhost:4200/assets/vendor.js:125:11)
    at requireModule (http://localhost:4200/assets/vendor.js:135:17)
    at require (http://localhost:4200/assets/blanket-loader.js:128:16)
    at http://localhost:4200/assets/sf-todo.js:1201:23
    at mod.state (http://localhost:4200/assets/vendor.js:150:29)
    at tryFinally (http://localhost:4200/assets/vendor.js:30:14)
    at requireModule (http://localhost:4200/assets/vendor.js:148:5)
    at require (http://localhost:4200/assets/blanket-loader.js:128:16)
    at oldLoader (http://localhost:4200/assets/blanket-loader.js:84:13)
    at Object._blanket.extend.utils.processFile (http://localhost:4200/assets/test-support.js:12100:17)
```

I'm not sure of the exact problem, but perhaps this is related.  [yadda-0.15.4](https://github.com/acuminous/yadda/blob/master/dist/yadda-0.15.4.js) sets the global 'require' to its own function when it is loaded.  This changes it from pointing to the usual ember-cli loader.js require function.  This doesn't seem to  be a problem when ember-cli-blanket coverage is off, although the global 'require' stays as the yadda function instead of the loader.js function for the rest of the load process.

But, when ember-cli-blanket coverage is on, ember-cli-blanket sets the global 'require' to its own function, which internally turn calls the global 'requirejs', which is the loader.js require function.
- note it the add-on doing this, not blanket.js itself
- normally the global 'require' and 'requirejs' both point to the loader.js function, but yadda changes that

That's a little confusing to explain, but its seems ember-cli-blanket ends up calling a different require function that what was used to load yadda.  If a different registry is used in each function, then 'yadda' may not be found.

Has anyone else seen this?  Ideas on how to fix?

**Comment by remkoboschker** [comment]
This pull request should solve the require issue for blanket https://github.com/sglanzer/ember-cli-blanket/pull/104 I hope I can find the time to have a look at a work-around for yadda.

**Comment by sfbwalder** [comment]
This is now irrelevant, closing.
